name: ReactPhp test
on:
  workflow_dispatch:

jobs:
  test-react-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install React and dependencies
        run: npm install
      - name: run the app
        run: npm run dev
